#!/usr/bin/env python3
"""Generates src/crmath_tables.rs (constants of the correctly rounded log/exp in crmath.rs).

    python3 crates/simoxide-random/scripts/crmath_tables.py > crates/simoxide-random/src/crmath_tables.rs
    rustfmt crates/simoxide-random/src/crmath_tables.rs

Only Python's decimal module is used (60 significant digits); float(Decimal) rounds correctly.
"""
import struct
from decimal import Decimal as D, getcontext

getcontext().prec = 60
LN2 = D(2).ln()


def bits(x):
    return struct.unpack('<Q', struct.pack('<d', x))[0]


def dd(v):
    hi = float(v)
    return hi, float(v - D(hi))


def truncated(v, sig):
    """v rounded to `sig` significant bits."""
    e = 0
    while abs(v) >= 2:
        v /= 2
        e += 1
    while abs(v) < 1:
        v *= 2
        e -= 1
    r = float(round(v * 2 ** (sig - 1)) / D(2 ** (sig - 1)))
    return r * 2.0 ** e


def split3(v, sig):
    a = truncated(v, sig)
    b = float(v - D(a))
    c = float(v - D(a) - D(b))
    return a, b, c


def c(x):
    return f'f64::from_bits(0x{bits(x):016x})'


out = ['//! Constants of [`crate::crmath`]. Generated by `scripts/crmath_tables.py`; do not edit.', '']

# ln 2 in three parts; the first has 42 significant bits, so k * LN2_1 is exact for |k| < 2^11.
l1, l2, l3 = split3(LN2, 42)
out += [f'pub(crate) const LN2_1: f64 = {c(l1)};', f'pub(crate) const LN2_2: f64 = {c(l2)};',
        f'pub(crate) const LN2_3: f64 = {c(l3)};']
# ln 2 / 64 in three parts; the first has 36 significant bits, so n * LN2_64_1 is exact for
# |n| < 2^17.
m1, m2, m3 = split3(LN2 / 64, 36)
out += [f'pub(crate) const LN2_64_1: f64 = {c(m1)};', f'pub(crate) const LN2_64_2: f64 = {c(m2)};',
        f'pub(crate) const LN2_64_3: f64 = {c(m3)};',
        f'pub(crate) const INV_LN2_64: f64 = {c(float(64 / LN2))};', '']

out += ['/// `2^(j/64)` as `(hi, lo)`, j = 0..63.', 'pub(crate) const EXP2_64: [(f64, f64); 64] = [']
for j in range(64):
    hi, lo = dd((D(j) / 64 * LN2).exp())
    out.append(f'    ({c(hi)}, {c(lo)}),')
out += ['];', '']

# log: x = 2^k m with m in [1, 2), i = top 7 mantissa bits. For i >= 52 (m >= 1.40625) the
# reduction uses m / 2 and k + 1, so that log x for x near 1 involves no cancellation.
# c_i ~ 1 / (bucket centre) with 8 significant bits (so that m * c_i - 1 is exact), 1 for the two
# buckets next to 1; the table holds c_i and -ln(c_i) as (hi, lo).
out += ['/// `(c_i, -ln(c_i) hi, -ln(c_i) lo)`, i = 0..127 (see `crmath::log`).',
        'pub(crate) const LOG_INV: [(f64, f64, f64); 128] = [']
worst = 0
for i in range(128):
    lo_edge, hi_edge = 1 + D(i) / 128, 1 + D(i + 1) / 128
    if i >= 52:
        lo_edge, hi_edge = lo_edge / 2, hi_edge / 2
    if i in (0, 127):
        ci = 1.0
    else:
        ci = truncated(1 / ((lo_edge + hi_edge) / 2), 8)
    if ci != 1.0:  # m * 1 - 1 is exact anyway
        worst = max(worst, abs(lo_edge * D(ci) - 1), abs(hi_edge * D(ci) - 1))
    h, l = dd(-D(ci).ln()) if ci != 1.0 else (0.0, 0.0)
    out.append(f'    ({c(ci)}, {c(h)}, {c(l)}),')
out += ['];']
# |m c_i - 1| < 2^-7 and m c_i a multiple of 2^-60: m c_i - 1 fits in 53 bits
assert worst < D(2) ** -7, worst
print('\n'.join(out))
